import type { Metadata } from "next";
import ToolPageLayout from "../ToolPageLayout";

export const metadata: Metadata = {
  title: "Add Audio - AI Audio Generator for Videos | NightWaveAI",
  description:
    "Add AI-generated audio to your videos. Generate sound effects, music, and ambient audio that perfectly matches your video content.",
  openGraph: {
    title: "Add Audio - AI Audio Generator for Videos | NightWaveAI",
    description: "Add AI-generated audio to your videos with perfect sync.",
    type: "website",
  },
};

const SAMPLE_OUTPUTS = [
  {
    title: "Thunderstorm",
    prompt: "Add realistic thunder and rain sounds to this night cityscape timelapse",
    gradient: "from-emerald-900/60 via-teal-900/40 to-zinc-900",
  },
  {
    title: "Synthwave Beat",
    prompt: "Retro 80s synthwave beat with driving bass for this neon driving sequence",
    gradient: "from-purple-900/60 via-fuchsia-900/40 to-zinc-900",
  },
  {
    title: "Forest Ambient",
    prompt: "Peaceful forest sounds with birdsong and a gentle stream for nature scenes",
    gradient: "from-green-900/60 via-lime-900/40 to-zinc-900",
  },
];

export default function AddAudioPage() {
  return (
    <ToolPageLayout
      toolIcon="🔊"
      toolName="Add Audio"
      toolBadge="Add Audio"
      badgeGradient="from-emerald-500 to-teal-600"
      description="Give your silent videos a voice. Upload a video and describe the audio you want — from realistic sound effects to full music tracks — all generated by AI in perfect sync."
      inputPlaceholder="Describe the audio you want to add..."
      inputHint='Try: "Cinematic orchestral score building to a crescendo, with subtle wind and ambient city sounds in the background"'
      sampleOutputs={SAMPLE_OUTPUTS}
    />
  );
}
